server:
  port: ${port:8080}


spring:
  cloud:
    gateway:
      routes:
        # path Rewrite API..
        - id: kko-mydoc-api
          uri: ${route_uri:http://localhost:18090}
          predicates:
            - Path=/v1/tokens,/v1/documents/status
          filters:
            - name: RewriteFilter
              args:
#                listMapExample:
#                  - name: local
#                    ip: 127.0.0.1
#                  - name: prod
#                    ip: 211.0.0.1
                mConf:
                    /v1/tokens:
                      rewrite_path: /v1/{X-Xit-DBUuid}/tokens/{X-Xit-Ott}
                      params:
                        - X-Xit-DBUuid
                        - X-Xit-Ott
                    /v1/documents/status:
                      rewrite_path: /v1/documents/{X-Xit-DBUuid}/status
                      params:
                        - X-Xit-DBUuid
        # By Pass API...
        - id: all
          uri: ${route_uri:http://localhost:18090}
          predicates:
            - Path=/**

  # ===================================================================================================================================
  # PID 설정
  # ===================================================================================================================================
  pid:
    file: proxyens.pid



# ===================================================================================================================================
# Logging 설정
# ===================================================================================================================================
logging:
  charset:
    console: utf-8
    file: utf-8
  level:
    root: info
  #    '[org.hibernate.sql]': info
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}){green} %clr([%18thread]){magenta} %clr(%-40.40logger{39}%line){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  file:
    name: ./logs/logback.log
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
      #보관일수
      max-history: 30
      #용량제한
      max-file-size: 100MB
